### ISSUE TITLE
Add note on how to use with @SpringBootTest if non-mocked

### ISSUE THREAD

**Issue by wimdeblauwe** [ch4mpy/spring-addons#147]
I had a hard time to figure out why my `@SpringBootTest(webEnvironment = RANDOM_PORT)` was not working as expected.

It turned out that `com.c4_soft.springaddons.security.oauth2.test.webmvc.AddonsWebmvcTestConf` was enabled by default. The fix was easy once I understood the problem, I just added an exclusion like this:

```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@EnableAutoConfiguration(exclude = AddonsWebmvcTestConf.class)
```

Maybe you can take the answer you gave at https://github.com/ch4mpy/spring-addons/discussions/76 in the section "How do I run my integration tests in non mocked environment" and add it to the readme and also include that people should add this exclusion to make sure everything works properly.

**Comment by ch4mpy** [comment]
Or, maybe, this test configuration should not be automatically applied.

You are running your test with a real authorization server in a container, right?

**Comment by wimdeblauwe** [comment]
Yeah, that would be even better.

Yes, I am using Keycloak in testcontainers via [testcontainers-keycloak](https://github.com/dasniko/testcontainers-keycloak).

**Comment by ch4mpy** [comment]
@wimdeblauwe I removed the Spring Boot auto loading resource from `spring-addons-starter-oidc-test`. If you still have a clone of this repo somewhere, would you `pull` the latest code and give a try with the `4.1.9-SNAPSHOT`?

Also, did you give a try to the [recently added @WithJwt](https://github.com/ch4mpy/spring-addons#211-using-withjwt-or-withopaquetoken-with-json-claim-sets)? It uses most of the runtime security beans to build the security context from the JSON payload of JWTs. Only the decoding is skipped. I haven't run performance evaluation tests, but I believe tests containers to be much slower.

**Comment by wimdeblauwe** [comment]
Thanks, it works with 7.1.9 without the exclusion!

I saw the `@WithJwt`, but for this particular test (which tests that there is an error response if the payload size is too big), I needed to have the actual Tomcat running, it is not possible to use MockMvc.

About that `@WithJwt`: How does that work with time expiration? If I would enable validation of the expiry time (not sure if that is enabled by default), wouldn't that make it impossible to use this as all the tokens will be expired? If not, how would I use them to test expiry?

**Comment by ch4mpy** [comment]
The expiry as well as token signature and optional issuer and audience are checked inside the JWT decoder which is the only part mocked. With `@WithJwt`, the process starts as normal just after the token decoding (with authentication manager and converter). So no, neither expiry, signature, audience or issuer will be checked. But the type `Authentication` as well as authorities mapping (and other claims if anything special is done during JWT to authentication conversion), happens as normal (as opposed to the former annotations where the authorities were declared and could be incoherent with the mocked claims).

I'm closing since your problem with test containers is solved. Thank you for reporting and testing. Do not hesitate to open a discussion or another issue if usage of the new annotations is not clear.

**Comment by ch4mpy** [comment]
@wimdeblauwe just thinking of it, but instead of the `password` flow in your test, you could consider using `client_credentials`.

If you want to emulate a user login with `authorization_code` flow, then maybe should you consider using protractor or another framework designed to emulate user interaction with browser, mouse and keyboard.

But as a resource server just doesn't care about the flow used to get a token, `client_credentials` options seems the most adapted.

**Comment by wimdeblauwe** [comment]
But with `client_credentials`, you log on as an application, not as a user like with `authorization_code` or `password` flows.

**Comment by ch4mpy** [comment]
Who cares? The flow used is a concern only for the OAuth2 client and the OAuth2 authorization server. As I just wrote, **from the resource server point of view an access token is an access token**, and all that matters is if this token is valid (and if it should grant access to the resource based on the claims in the token). How the token was obtained (`client_credentials`, `authorization_code`, `refresh_token`, etc. is of no importance, and actually, it has no real way to know).

**Comment by wimdeblauwe** [comment]
True. I would just need to check to give that client the roles the user would have.
