### ISSUE TITLE
Ability to configure exceptionHandling functionality for com.c4-soft.springaddons.oidc.resourceserver

### ISSUE THREAD

**Issue by nexus061** [ch4mpy/spring-addons#151]
Hi, It would be useful to be able to configure the class that handles exceptions with the 401 status, if I want I can make a pull request

**Comment by ch4mpy** [comment]
Sure, you can propose a pull request, even if it still an early draft. I can provid support the polish it.

If you have something ready, we can talk about features based on it.

Otherwise, what features do you target exactly?

**Comment by nexus061** [comment]
`http.exceptionHandling(exceptionHandling -> exceptionHandling.authenticationEntryPoint((request, response, authException) -> {
			response.addHeader(HttpHeaders.WWW_AUTHENTICATE, "Bearer realm=\"Restricted Content\"");
			response.sendError(HttpStatus.UNAUTHORIZED.value(), HttpStatus.UNAUTHORIZED.getReasonPhrase());
		}));`

I would like to define my class for this feature, so that I can command the response message, I'm seeing that there is the ResourceServerHttpSecurityPostProcessor interface, maybe with this you don't need to modify; My idea was to look for a bean for exception handling if found to use that, otherwise go ahead as normal. What do you think?

**Comment by ch4mpy** [comment]
I suggest we define a `@ConditionalOnMissingBean` implementing `ExceptionHandlingConfigurer<HttpSecurity>` with the code of the lambda you just found.

If we have this bean injected in `springAddonsJwtResourceServerSecurityFilterChain` and `springAddonsIntrospectingResourceServerSecurityFilterChain` and cascade it down to `ServletConfigurationSupport::configureResourceServer`, Spring-addons users would have no more to do than define their own `ExceptionHandlingConfigurer<HttpSecurity>` bean somewhere in their conf.

Note that the something similar should be applied to reactive implementations (in `ReactiveSpringAddonsOidcResourceServerBeans` to enable configuration of the all `ExceptionHandlingSpec` (instead of just the `ServerAccessDeniedHandler`).

Do you prefer to make the PR by yourself (and be contributor), or do you want me to out this together (I have time to release it within the next 12 hours)?

**Comment by nexus061** [comment]
Hi, i have done pull request https://github.com/ch4mpy/spring-addons/pull/152

**Comment by ch4mpy** [comment]
Released with `7.1.11` which should be available shortly from maven-central

**Comment by ch4mpy** [comment]
@nexus061 this is finally released as `7.1.12`. I just checked on [maven-central](https://repo1.maven.org/maven2/com/c4-soft/springaddons/spring-addons-starter-oidc/7.1.12/), the release is publicly available.

Something went wrong when releasing yesterday and I believe that for some reason the version was labeled `git` instead of `7.1.11`...

**Comment by nexus061** [comment]
> @nexus061 this is finally released as `7.1.12`. I just checked on [maven-central](https://repo1.maven.org/maven2/com/c4-soft/springaddons/spring-addons-starter-oidc/7.1.12/), the release is publicly available.
> 
> Something went wrong when releasing yesterday and I believe that for some reason the version was labeled `git` instead of `7.1.11`...

great!
