### ISSUE TITLE
Principal

### ISSUE THREAD

**Issue by arnonuem** [ch4mpy/spring-addons#17]
Hi how would i inject the principal in the testcase?

On my controller i have something like:
``` 
@GetMapping
fun something(principal: UsernamePasswordAuthenticationToken) {
   ...
}
```

where `UsernamePasswordAuthenticationToken` is type of `org.springframework.security.core.Authentication`

In my security config i have registered a converter which transforms the jwt to this token.
Would be glad if you could come up with a hint on this.

When i write my test like:
```
    @Test
    @WithMockAuthentication(UsernamePasswordAuthenticationToken::class)
    fun `should do`() {
        client.mutateWith(mockAuthentication(UsernamePasswordAuthenticationToken::class.java)) ......
    }
```
Where can i then influence the mock of UsernamePasswordAuthenticationToken i am using. I need to set the `.details` field with an AppUser because i am using a Converter in my security config like i stated above.

When i debug it i see that i am getting a `UsernamePasswordAuthenticationToken$MockitoMock$...` and the fields are set as follows:
```
principal = null
credentials = null
authorities = null
details = null
authenticated = false
```

**Comment by arnonuem** [comment]
Ok i just found the solution to this. This repo could need some more documentation :D
In my case instead of using:
```
mockAuthentication(UsernamePasswordAuthenticationToken::class.java)
```
i had to just modify it to
```
val details = AppUserJwtAuthConverter.AppUserData("full.name@fake.mail", "fn", "Full", "Name")
mockAuthentication(UsernamePasswordAuthenticationToken::class.java).details(details)
```
And now the converter is also respected :)
Thanks a lot for that great repo. And please update your documentation in regards to the builder pattern with some more examples ;)

**Comment by ch4mpy** [comment]
Did you have a look at `@WithMockAuthentication` javadoc?

If the actual `Authentication` impl type is of no importance (because you're only doing role-based security for instance), something like `@WithMockAuthentication(name = "Ch4mpy", authorities = { "ROLE_TESTER", "ROLE_AUTHOR" })` should be just enough.

For `UsernamePasswordAuthenticationToken`, isn't Spring's `@WithMockUser` more convenient to use ?

I'm not sure I understood your use-case: `UsernamePasswordAuthenticationToken` really is bad `Authentication` impl when parsing a `JWT`. I'd suggest you to use Spring's `JwtAuthenticationToken`, Keycloak's `KeycloakAuthenticationToken`, my `OidcIdAuthenticationToken` or an implementation of your own (not so complicated actually)

**Comment by arnonuem** [comment]
Hi, thanks for your insights. Actually this is not my project and i have to take what is there. So i am a bit stuck on that. But now all works nice an smooth. I gave you also a credit on stackoverflow :)


17. Feb. 2021, 03:29 von notifications@github.com:
