### ISSUE TITLE
Docs: multi-tenancy tutorial readme needs an update, and trouble upgrading

### ISSUE THREAD

**Issue by draial** [ch4mpy/spring-addons#236]
Hi! Thanks for putting open-source code out there. I appreciate you.

## Issue

Re: spring-addons-starter-oidc: [this multi-tenancy tutorial](https://github.com/ch4mpy/spring-addons/tree/master/samples/tutorials/resource-server_multitenant_dynamic#readme) seems out of date: it says to extend `SpringAddonsSecurityProperties`, but the class does not exist, for instance.

### Trouble upgrading

I'm trying to upgrade from a working config that uses `7.1.8`, all the way up to `8.0.0`. [The `Migrating from 7.x to 8.x` guide](https://github.com/ch4mpy/spring-addons/blob/master/migrate-to-8.0.0.md) does not mention those changes.

---

I would provide my `SecurityConfig.java`, but it's almost exactly just the code of [this multi-tenancy tutorial](https://github.com/ch4mpy/spring-addons/tree/master/samples/tutorials/resource-server_multitenant_dynamic#readme), linting aside

If you or anyone could provide some assistance and advice (or point me to current documentation if I missed it), I would appreciate it greatly.

**Comment by ch4mpy** [comment]
It looks like this tutorial README is completely deprecated. 

Until it is fixed, you may:
- to understand how dynamic multi-tenancy works for resource servers with spring-addons, refer to [spring-addons-starter-oidc manual](https://github.com/ch4mpy/spring-addons/tree/master/spring-addons-starter-oidc#1-1-4)
- for a working sample, do as instructed in [the disclaimer this README contains](https://github.com/ch4mpy/spring-addons/tree/master/samples/tutorials/resource-server_multitenant_dynamic#0-disclaimer) and use the code in the source of the tutorial instead of the README. But be aware that this is just a sample and that many other strategies could be implemented to resolve issuer properties.

**Comment by ch4mpy** [comment]
@draial please confirm that the tutorial README update is enough - and close this ticket if that's the case.

**Comment by draial** [comment]
Just to let you know that I've made it work thanks to your help. Thanks again!
